/* ============================================================
 * app.js — ESM 模組唯一入口（facade 安裝器）
 * ------------------------------------------------------------
 * 由 system.html 以 <script type="module"> 載入。匯入已遷移的
 * 領域模組，並把其公開函式以【與舊全域 1:1 的名字】掛回 window，
 * 使 HTML inline on* 屬性、system.js 與其他 classic 腳本的裸呼叫
 * 完全不受影響。
 *
 * 新增領域遷移時：import 該領域 → 在 FACADE 補上同名對應。
 * ============================================================ */

import * as Print from './domains/print/index.js';
import * as Wallet from './domains/wallet/index.js';
import * as Auth from './domains/auth/index.js';
import * as Patients from './domains/patients/index.js';
import * as Billing from './domains/billing/index.js';
import * as Consultation from './domains/consultation/index.js';

const FACADE = {
    // ── print（收據／應診證明／病假紙／處方指示）──────────────
    printReceiptFromAppointment: Print.printReceiptFromAppointment,
    printAttendanceCertificateFromAppointment: Print.printAttendanceCertificateFromAppointment,
    printSickLeaveFromAppointment: Print.printSickLeaveFromAppointment,
    printConsultationRecord: Print.printConsultationRecord,
    printAttendanceCertificate: Print.printAttendanceCertificate,
    printSickLeave: Print.printSickLeave,
    printPrescriptionInstructionsFromAppointment: Print.printPrescriptionInstructionsFromAppointment,
    printPrescriptionInstructions: Print.printPrescriptionInstructions,

    // ── wallet（會員儲值：帳戶／面板／充值退款調整／配置／診症支付）──
    loadWalletManagement: Wallet.loadWalletManagement,
    clearWalletCaches: Wallet.clearWalletCaches,
    runWalletLegacyMigration: Wallet.runWalletLegacyMigration,
    selectWalletPatient: Wallet.selectWalletPatient,
    getWalletAccount: Wallet.getWalletAccount,
    getRecentWalletTransactions: Wallet.getRecentWalletTransactions,
    walletRound2: Wallet.walletRound2,
    submitWalletTopup: Wallet.submitWalletTopup,
    submitWalletRefund: Wallet.submitWalletRefund,
    submitWalletAdjust: Wallet.submitWalletAdjust,
    submitWalletStatus: Wallet.submitWalletStatus,
    showWalletRefundForm: Wallet.showWalletRefundForm,
    hideWalletAdminForm: Wallet.hideWalletAdminForm,
    showWalletAdjustForm: Wallet.showWalletAdjustForm,
    showWalletStatusForm: Wallet.showWalletStatusForm,
    toggleWalletConfigForm: Wallet.toggleWalletConfigForm,
    addWalletTierRow: Wallet.addWalletTierRow,
    removeWalletTierRow: Wallet.removeWalletTierRow,
    submitWalletConfig: Wallet.submitWalletConfig,
    walletGoToTxPage: Wallet.walletGoToTxPage,
    toggleWalletAdminOps: Wallet.toggleWalletAdminOps,
    setupConsultationWallet: Wallet.setupConsultationWallet,
    syncConsultWalletAvailability: Wallet.syncConsultWalletAvailability,
    processConsultationWalletPayment: Wallet.processConsultationWalletPayment,
    retryConsultationWalletPayment: Wallet.retryConsultationWalletPayment,
    cancelConsultationWalletPayment: Wallet.cancelConsultationWalletPayment,
    preCheckConsultationWalletPayment: Wallet.preCheckConsultationWalletPayment,

    // ── auth（登入工作階段／帳號安全／授權索引／員工與權限管理）──
    // session：主登入、登入後同步、登出清理、本機快取清除、改密碼／自我封存
    loadAccountSecurity: Auth.loadAccountSecurity,
    changeCurrentUserPassword: Auth.changeCurrentUserPassword,
    archiveCurrentUserAccount: Auth.archiveCurrentUserAccount,
    attemptMainLogin: Auth.attemptMainLogin,
    syncUserDataFromFirebase: Auth.syncUserDataFromFirebase,
    clearLocalClinicData: Auth.clearLocalClinicData,
    detachAllKnownFirestoreListeners: Auth.detachAllKnownFirestoreListeners,
    shutdownFirestoreAndWipePersistence: Auth.shutdownFirestoreAndWipePersistence,
    reloadPageSoon: Auth.reloadPageSoon,
    wipeDeviceDataAndReload: Auth.wipeDeviceDataAndReload,
    logout: Auth.logout,
    openSidebar: Auth.openSidebar,
    closeSidebar: Auth.closeSidebar,
    toggleSidebar: Auth.toggleSidebar,
    IDB_PHI_MARKER: Auth.IDB_PHI_MARKER,
    IDB_WIPE_ATTEMPTED: Auth.IDB_WIPE_ATTEMPTED,

    // claims：後端 admin API 封裝、Auth 帳號生命週期、授權索引同步
    getAuthorizedUserFromIndex: Auth.getAuthorizedUserFromIndex,
    upsertAuthorizedUserIndex: Auth.upsertAuthorizedUserIndex,
    removeAuthorizedUserIndex: Auth.removeAuthorizedUserIndex,
    callAdminClaimsApi: Auth.callAdminClaimsApi,
    createStaffAuthAccount: Auth.createStaffAuthAccount,
    syncStaffClaims: Auth.syncStaffClaims,
    deleteStaffAuthAccount: Auth.deleteStaffAuthAccount,
    archiveStaffAuthAccount: Auth.archiveStaffAuthAccount,
    bootstrapAllUserClaims: Auth.bootstrapAllUserClaims,
    fetchLegacyAuthorizedUserByUidOrEmail: Auth.fetchLegacyAuthorizedUserByUidOrEmail,
    fetchAuthorizedUserByUidOrEmail: Auth.fetchAuthorizedUserByUidOrEmail,

    // staff：用戶 CRUD、啟用／封存／復職、職位權限面板、診所名額
    getClinicIdForUser: Auth.getClinicIdForUser,
    getClinicUserLimitGroup: Auth.getClinicUserLimitGroup,
    getClinicUserLimitLabel: Auth.getClinicUserLimitLabel,
    canActivateUserUnderClinicLimit: Auth.canActivateUserUnderClinicLimit,
    getPrimaryClinicNameForUser: Auth.getPrimaryClinicNameForUser,
    loadUserManagement: Auth.loadUserManagement,
    loadPermissionManagementPanel: Auth.loadPermissionManagementPanel,
    onPermissionPositionChanged: Auth.onPermissionPositionChanged,
    saveSelectedPositionPermissions: Auth.saveSelectedPositionPermissions,
    loadUsersFromFirebase: Auth.loadUsersFromFirebase,
    filterUsers: Auth.filterUsers,
    displayUsers: Auth.displayUsers,
    showAddUserForm: Auth.showAddUserForm,
    hideAddUserForm: Auth.hideAddUserForm,
    clearUserForm: Auth.clearUserForm,
    setUserEmailFieldEditable: Auth.setUserEmailFieldEditable,
    toggleRegistrationNumberField: Auth.toggleRegistrationNumberField,
    editUser: Auth.editUser,
    saveUser: Auth.saveUser,
    toggleUserStatus: Auth.toggleUserStatus,
    patchLocalUserRecord: Auth.patchLocalUserRecord,
    archiveUser: Auth.archiveUser,
    restoreUser: Auth.restoreUser,

    // ── patients 資料層（分頁快取讀取＋多人同步基礎設施）──
    PATIENTS_CACHE_TTL_MS: Patients.PATIENTS_CACHE_TTL_MS,
    fetchPatients: Patients.fetchPatients,
    getPatientByIdWithRefresh: Patients.getPatientByIdWithRefresh,
    fetchPatientsPage: Patients.fetchPatientsPage,
    fetchPatientsPageAsc: Patients.fetchPatientsPageAsc,
    comparePatientsByNumberDesc: Patients.comparePatientsByNumberDesc,
    fetchPatientsPageOptimized: Patients.fetchPatientsPageOptimized,
    getPatientsCount: Patients.getPatientsCount,
    newSelfMetaNonce: Patients.newSelfMetaNonce,
    isSelfMetaNonce: Patients.isSelfMetaNonce,
    metaTimestampToMillis: Patients.metaTimestampToMillis,
    readPatientsStorageMeta: Patients.readPatientsStorageMeta,
    writePatientsStorageMeta: Patients.writePatientsStorageMeta,
    stampPatientsStorageMetaTimestamp: Patients.stampPatientsStorageMetaTimestamp,
    resetPatientPaginationCaches: Patients.resetPatientPaginationCaches,
    adjustPatientsCountCache: Patients.adjustPatientsCountCache,
    reloadVisiblePatientList: Patients.reloadVisiblePatientList,
    invalidateAllPatientCaches: Patients.invalidateAllPatientCaches,
    isPatientIdInFullCaches: Patients.isPatientIdInFullCaches,
    handleRemotePatientMetaChange: Patients.handleRemotePatientMetaChange,
    attachPatientListListener: Patients.attachPatientListListener,
    detachPatientListListener: Patients.detachPatientListListener,
    touchPatientsMeta: Patients.touchPatientsMeta,
    attachPatientConsultationsListener: Patients.attachPatientConsultationsListener,
    detachPatientConsultationsListener: Patients.detachPatientConsultationsListener,

    // ── patients 列表與搜尋（Phase 4 子批 A）──
    loadPatientListFromFirebase: Patients.loadPatientListFromFirebase,
    loadPatientList: Patients.loadPatientList,
    renderPatientListTable: Patients.renderPatientListTable,
    renderPatientListPage: Patients.renderPatientListPage,

    // ── patients 詳情（Phase 4 子批 B）──
    viewPatient: Patients.viewPatient,

    // ── patients 病歷歷史 UI（Phase 4 子批 C）──
    getHistoryCalendarContextPatientId: Patients.getHistoryCalendarContextPatientId,
    getHistoryCalendarContextList: Patients.getHistoryCalendarContextList,
    getHistoryCalendarContextPage: Patients.getHistoryCalendarContextPage,
    renderHistoryCalendar: Patients.renderHistoryCalendar,
    closeHistoryCalendar: Patients.closeHistoryCalendar,
    openHistoryCalendarAtCurrentMonth: Patients.openHistoryCalendarAtCurrentMonth,
    buildHistoryDateSelectionHtml: Patients.buildHistoryDateSelectionHtml,
    buildHistoryCalendarHtml: Patients.buildHistoryCalendarHtml,
    toggleHistoryCalendar: Patients.toggleHistoryCalendar,
    changeHistoryCalendarMonth: Patients.changeHistoryCalendarMonth,
    jumpToHistoryCalendarIndex: Patients.jumpToHistoryCalendarIndex,
    resolveHistoryCalendarJump: Patients.resolveHistoryCalendarJump,
    selectHistoryCalendarDate: Patients.selectHistoryCalendarDate,
    selectHistoryCalendarRecord: Patients.selectHistoryCalendarRecord,
    showPatientMedicalHistory: Patients.showPatientMedicalHistory,
    getMedicalHistoryActionButtonClasses: Patients.getMedicalHistoryActionButtonClasses,
    renderMedicalHistoryActionButton: Patients.renderMedicalHistoryActionButton,
    renderMedicalHistoryActionButtons: Patients.renderMedicalHistoryActionButtons,
    displayPatientMedicalHistoryPage: Patients.displayPatientMedicalHistoryPage,
    changePatientHistoryPage: Patients.changePatientHistoryPage,
    closePatientMedicalHistoryModal: Patients.closePatientMedicalHistoryModal,
    viewPatientMedicalHistory: Patients.viewPatientMedicalHistory,
    displayConsultationMedicalHistoryPage: Patients.displayConsultationMedicalHistoryPage,

    // ── billing 收費項目同步與管理（Phase 5 子批 A）──
    stopBillingItemsRealtimeSync: Billing.stopBillingItemsRealtimeSync,
    mergeBillingItemsFromRealtime: Billing.mergeBillingItemsFromRealtime,
    ensureBillingItemsRealtimeSync: Billing.ensureBillingItemsRealtimeSync,
    initBillingItems: Billing.initBillingItems,
    loadBillingManagement: Billing.loadBillingManagement,
    filterBillingItems: Billing.filterBillingItems,
    displayBillingItems: Billing.displayBillingItems,
    createBillingItemCard: Billing.createBillingItemCard,
    showAddBillingItemForm: Billing.showAddBillingItemForm,
    hideAddBillingItemForm: Billing.hideAddBillingItemForm,
    clearBillingItemForm: Billing.clearBillingItemForm,
    editBillingItem: Billing.editBillingItem,
    saveBillingItem: Billing.saveBillingItem,
    deleteBillingItem: Billing.deleteBillingItem,

    // ── billing 套票（Phase 5 子批 B：診所隔離／購銷／歷史／面板）──
    currentPackageClinicId: Billing.currentPackageClinicId,
    resolvePatientDetailClinic: Billing.resolvePatientDetailClinic,
    filterPackagesByClinic: Billing.filterPackagesByClinic,
    ensurePatientPackagesClinicScoped: Billing.ensurePatientPackagesClinicScoped,
    ensurePatientPackageHistoryClinicScoped: Billing.ensurePatientPackageHistoryClinicScoped,
    getPatientPackages: Billing.getPatientPackages,
    getPackageHistoryOperatorUsername: Billing.getPackageHistoryOperatorUsername,
    getPackageHistoryOperatorDisplayName: Billing.getPackageHistoryOperatorDisplayName,
    normalizePackageHistoryLogs: Billing.normalizePackageHistoryLogs,
    createPackageHistoryLog: Billing.createPackageHistoryLog,
    appendPackageHistoryLog: Billing.appendPackageHistoryLog,
    withPackageHistoryLog: Billing.withPackageHistoryLog,
    getPackageHistoryLogsForDisplay: Billing.getPackageHistoryLogsForDisplay,
    formatPackageHistoryTimestamp: Billing.formatPackageHistoryTimestamp,
    formatPackageHistoryDateOnly: Billing.formatPackageHistoryDateOnly,
    getPackageHistoryDateObject: Billing.getPackageHistoryDateObject,
    getPackageHistorySummary: Billing.getPackageHistorySummary,
    getPackageHistoryTypeLabel: Billing.getPackageHistoryTypeLabel,
    getPackageHistorySourceLabel: Billing.getPackageHistorySourceLabel,
    buildPatientPackageHistoryRecord: Billing.buildPatientPackageHistoryRecord,
    buildLegacyPatientPackageHistoryEntries: Billing.buildLegacyPatientPackageHistoryEntries,
    invalidatePatientPackageHistoryCaches: Billing.invalidatePatientPackageHistoryCaches,
    resolvePackageHistoryClinicId: Billing.resolvePackageHistoryClinicId,
    getClinicNameById: Billing.getClinicNameById,
    recordPatientPackageHistory: Billing.recordPatientPackageHistory,
    getPatientPackageHistoryLocaleState: Billing.getPatientPackageHistoryLocaleState,
    renderPatientPackageHistoryEntriesHtml: Billing.renderPatientPackageHistoryEntriesHtml,
    updatePatientPackageHistoryModalPagination: Billing.updatePatientPackageHistoryModalPagination,
    loadPatientPackageHistoryPage: Billing.loadPatientPackageHistoryPage,
    purchasePackage: Billing.purchasePackage,
    consumePackage: Billing.consumePackage,
    consumePackageLocally: Billing.consumePackageLocally,
    formatPackageStatus: Billing.formatPackageStatus,
    createManualPatientPackage: Billing.createManualPatientPackage,
    updatePatientPackageExpiry: Billing.updatePatientPackageExpiry,
    deletePatientPackageRecord: Billing.deletePatientPackageRecord,
    updatePatientPackageRemainingUses: Billing.updatePatientPackageRemainingUses,
    renderPatientPackages: Billing.renderPatientPackages,
    showPatientPackageHistory: Billing.showPatientPackageHistory,
    renderPackageStatusSection: Billing.renderPackageStatusSection,
    renderPatientWalletStatus: Billing.renderPatientWalletStatus,
    renderPatientRecentWalletTxsHtml: Billing.renderPatientRecentWalletTxsHtml,
    openWalletManagementForPatient: Billing.openWalletManagementForPatient,
    refreshPatientPackagesUI: Billing.refreshPatientPackagesUI,
    useOnePackage: Billing.useOnePackage,
    undoPackageUse: Billing.undoPackageUse,
    restorePackageUseMeta: Billing.restorePackageUseMeta,

    // ── billing 支出（Phase 5 子批 C：分攤成本／匯入／CRUD）──
    monthsInDateRange: Billing.monthsInDateRange,
    getClinicExpensesByMonths: Billing.getClinicExpensesByMonths,
    getApportionedCost: Billing.getApportionedCost,
    showExpenseImportModal: Billing.showExpenseImportModal,
    closeExpenseImportModal: Billing.closeExpenseImportModal,
    saveClinicExpense: Billing.saveClinicExpense,
    listClinicExpensesForMonth: Billing.listClinicExpensesForMonth,
    bindClinicExpenseRowActions: Billing.bindClinicExpenseRowActions,
    loadClinicExpensesForSelectedMonth: Billing.loadClinicExpensesForSelectedMonth,
    loadClinicExpensesForListMonth: Billing.loadClinicExpensesForListMonth,
    showExpenseListModal: Billing.showExpenseListModal,
    closeExpenseListModal: Billing.closeExpenseListModal,
    startEditExpense: Billing.startEditExpense,
    saveEditExpense: Billing.saveEditExpense,
    cancelEditExpense: Billing.cancelEditExpense,
    deleteExpense: Billing.deleteExpense,

    // ── 財務報表（Phase 5 子批 D：快取／統計／圖表／鑽取／匯出／錢包財務）──
    getFinancialReportCacheKey: Billing.getFinancialReportCacheKey,
    projectFinancialRecordForCache: Billing.projectFinancialRecordForCache,
    buildFinancialCacheEntry: Billing.buildFinancialCacheEntry,
    readPersistedFinancialCache: Billing.readPersistedFinancialCache,
    writePersistedFinancialCache: Billing.writePersistedFinancialCache,
    pruneFinancialCacheMap: Billing.pruneFinancialCacheMap,
    setFinancialReportLoadingState: Billing.setFinancialReportLoadingState,
    loadFinancialReports: Billing.loadFinancialReports,
    formatFinancialDate: Billing.formatFinancialDate,
    financialDayStart: Billing.financialDayStart,
    financialDayEnd: Billing.financialDayEnd,
    getFinancialDateKey: Billing.getFinancialDateKey,
    shiftFinancialDate: Billing.shiftFinancialDate,
    enumerateFinancialDates: Billing.enumerateFinancialDates,
    scheduleFinancialReportRefresh: Billing.scheduleFinancialReportRefresh,
    runFinancialReportGuarded: Billing.runFinancialReportGuarded,
    loadFinancialDoctorOptions: Billing.loadFinancialDoctorOptions,
    loadFinancialClinicOptions: Billing.loadFinancialClinicOptions,
    loadUsersForFinancial: Billing.loadUsersForFinancial,
    loadConsultationsForFinancial: Billing.loadConsultationsForFinancial,
    setQuickDate: Billing.setQuickDate,
    normalizeFinancialCategory: Billing.normalizeFinancialCategory,
    parseFinancialBillingItems: Billing.parseFinancialBillingItems,
    cloneFinancialSummaryItems: Billing.cloneFinancialSummaryItems,
    buildConsultationFinancialSummaryPayload: Billing.buildConsultationFinancialSummaryPayload,
    getCurrentAuthUid: Billing.getCurrentAuthUid,
    callPersonalStatsApi: Billing.callPersonalStatsApi,
    callFinancialStatsApi: Billing.callFinancialStatsApi,
    normalizePersonalStatsString: Billing.normalizePersonalStatsString,
    clearPersonalStatisticsLocalCache: Billing.clearPersonalStatisticsLocalCache,
    normalizeFinancialRecordForReport: Billing.normalizeFinancialRecordForReport,
    getFinancialReportSyncTimestamp: Billing.getFinancialReportSyncTimestamp,
    getFinancialSummaryCoverageKey: Billing.getFinancialSummaryCoverageKey,
    getFinancialCategoryFromItemName: Billing.getFinancialCategoryFromItemName,
    generateFinancialReport: Billing.generateFinancialReport,
    aggregateFromDailyStats: Billing.aggregateFromDailyStats,
    filterFinancialConsultations: Billing.filterFinancialConsultations,
    fetchFinancialRecordsForRange: Billing.fetchFinancialRecordsForRange,
    attachPreviousPeriod: Billing.attachPreviousPeriod,
    loadFinancialPrevPeriodInBackground: Billing.loadFinancialPrevPeriodInBackground,
    financialChangePill: Billing.financialChangePill,
    calculateFinancialStatistics: Billing.calculateFinancialStatistics,
    getFinancialCategoryDisplayName: Billing.getFinancialCategoryDisplayName,
    updateFinancialKeyMetrics: Billing.updateFinancialKeyMetrics,
    updateFinancialTables: Billing.updateFinancialTables,
    updateFinancialCharts: Billing.updateFinancialCharts,
    showFinancialDrilldownLoading: Billing.showFinancialDrilldownLoading,
    fetchFinancialDrilldownRecords: Billing.fetchFinancialDrilldownRecords,
    openFinancialDrilldown: Billing.openFinancialDrilldown,
    closeFinancialDrilldown: Billing.closeFinancialDrilldown,
    updateFinancialSummaryTable: Billing.updateFinancialSummaryTable,
    updateFinancialDailyTable: Billing.updateFinancialDailyTable,
    updateFinancialDoctorTable: Billing.updateFinancialDoctorTable,
    updateFinancialServiceTable: Billing.updateFinancialServiceTable,
    walletFinRangeIso: Billing.walletFinRangeIso,
    walletFetchAllDocs: Billing.walletFetchAllDocs,
    loadWalletFinAggregates: Billing.loadWalletFinAggregates,
    loadWalletFinRaw: Billing.loadWalletFinRaw,
    getWalletFinRaw: Billing.getWalletFinRaw,
    buildWalletPatientClinicMap: Billing.buildWalletPatientClinicMap,
    calculateWalletFinancialStats: Billing.calculateWalletFinancialStats,
    walletFinFmt: Billing.walletFinFmt,
    updateWalletFinSection: Billing.updateWalletFinSection,
    loadWalletReceivables: Billing.loadWalletReceivables,
    renderWalletReceivables: Billing.renderWalletReceivables,
    refreshWalletFinancialSection: Billing.refreshWalletFinancialSection,
    markWalletReceivablePaid: Billing.markWalletReceivablePaid,
    switchFinancialTab: Billing.switchFinancialTab,
    buildFinancialExportPayload: Billing.buildFinancialExportPayload,
    exportFinancialReportTxt: Billing.exportFinancialReportTxt,
    exportFinancialReportExcel: Billing.exportFinancialReportExcel,

    // ── consultation 診症表單（Phase 6 子批 A：開方＋診症內收費）──
    searchHerbsForPrescription: Consultation.searchHerbsForPrescription,
    setActivePrescription: Consultation.setActivePrescription,
    addPrescriptionSection: Consultation.addPrescriptionSection,
    removePrescriptionSection: Consultation.removePrescriptionSection,
    renamePrescription: Consultation.renamePrescription,
    updatePrescriptionModeAt: Consultation.updatePrescriptionModeAt,
    clearActivePrescriptionItems: Consultation.clearActivePrescriptionItems,
    setActivePrescriptionItems: Consultation.setActivePrescriptionItems,
    getTotalMedicationDays: Consultation.getTotalMedicationDays,
    isForbiddenCombination: Consultation.isForbiddenCombination,
    displayPrescriptionError: Consultation.displayPrescriptionError,
    checkPrescriptionConflicts: Consultation.checkPrescriptionConflicts,
    updatePrescriptionTypeSelectStatus: Consultation.updatePrescriptionTypeSelectStatus,
    updateSinglePrescriptionModePlacement: Consultation.updateSinglePrescriptionModePlacement,
    addToPrescription: Consultation.addToPrescription,
    updatePrescriptionDisplay: Consultation.updatePrescriptionDisplay,
    updateMedicationDaysAt: Consultation.updateMedicationDaysAt,
    updateMedicationDays: Consultation.updateMedicationDays,
    updateMedicationFrequencyAt: Consultation.updateMedicationFrequencyAt,
    updateMedicationFrequency: Consultation.updateMedicationFrequency,
    updateMedicationFrequencyFromInputAt: Consultation.updateMedicationFrequencyFromInputAt,
    updateMedicineFeeByDays: Consultation.updateMedicineFeeByDays,
    getMedicineFeeDaysFromSelected: Consultation.getMedicineFeeDaysFromSelected,
    syncMedicationDaysWithMedicineFee: Consultation.syncMedicationDaysWithMedicineFee,
    updateMedicationDaysFromInputAt: Consultation.updateMedicationDaysFromInputAt,
    updateMedicationDaysFromInput: Consultation.updateMedicationDaysFromInput,
    updateRestPeriod: Consultation.updateRestPeriod,
    updatePrescriptionDosage: Consultation.updatePrescriptionDosage,
    updatePrescriptionDosageLive: Consultation.updatePrescriptionDosageLive,
    removePrescriptionItem: Consultation.removePrescriptionItem,
    updatePrescriptionDosageAt: Consultation.updatePrescriptionDosageAt,
    updatePrescriptionDosageLiveAt: Consultation.updatePrescriptionDosageLiveAt,
    removePrescriptionItemAt: Consultation.removePrescriptionItemAt,
    removePrescriptionSectionAt: Consultation.removePrescriptionSectionAt,
    clearPrescriptionSearch: Consultation.clearPrescriptionSearch,
    searchBillingForConsultation: Consultation.searchBillingForConsultation,
    getCategoryBgColor: Consultation.getCategoryBgColor,
    addToBilling: Consultation.addToBilling,
    updateBillingDisplay: Consultation.updateBillingDisplay,
    updateBillingQuantity: Consultation.updateBillingQuantity,
    removeBillingItem: Consultation.removeBillingItem,
    toggleDiscountEligibility: Consultation.toggleDiscountEligibility,
    clearBillingSearch: Consultation.clearBillingSearch,
    clearAllSearchFields: Consultation.clearAllSearchFields,
    addDefaultConsultationFee: Consultation.addDefaultConsultationFee,
    loadPreviousPrescription: Consultation.loadPreviousPrescription,
    parsePrescriptionToItems: Consultation.parsePrescriptionToItems,
    isFormulaName: Consultation.isFormulaName,
    loadPreviousBillingItems: Consultation.loadPreviousBillingItems,
    parseBillingItemsFromText: Consultation.parseBillingItemsFromText,
    loadMedicalRecordToCurrentConsultation: Consultation.loadMedicalRecordToCurrentConsultation,

    // ── consultation 儲存與表單生命週期（Phase 6 子批 B）──────────
    buildConsultationSymptomsDraftKey: Consultation.buildConsultationSymptomsDraftKey,
    buildLegacyConsultationSymptomsDraftKey: Consultation.buildLegacyConsultationSymptomsDraftKey,
    readConsultationSymptomsDraft: Consultation.readConsultationSymptomsDraft,
    writeConsultationSymptomsDraft: Consultation.writeConsultationSymptomsDraft,
    clearConsultationSymptomsDraft: Consultation.clearConsultationSymptomsDraft,
    getConsultationDraftHtmlText: Consultation.getConsultationDraftHtmlText,
    normalizeConsultationDraftPrescriptionSections: Consultation.normalizeConsultationDraftPrescriptionSections,
    normalizeConsultationDraftBillingItems: Consultation.normalizeConsultationDraftBillingItems,
    collectConsultationDraftPayload: Consultation.collectConsultationDraftPayload,
    hasMeaningfulConsultationDraft: Consultation.hasMeaningfulConsultationDraft,
    persistConsultationSymptomsDraft: Consultation.persistConsultationSymptomsDraft,
    restoreConsultationSymptomsDraft: Consultation.restoreConsultationSymptomsDraft,
    setupConsultationSymptomsDraftAutosave: Consultation.setupConsultationSymptomsDraftAutosave,
    stopConsultationSymptomsDraftAutosave: Consultation.stopConsultationSymptomsDraftAutosave,
    queueConsultationSymptomsDraftSave: Consultation.queueConsultationSymptomsDraftSave,
    updateConsultationCancelButtonLabel: Consultation.updateConsultationCancelButtonLabel,
    showConsultationForm: Consultation.showConsultationForm,
    clearConsultationForm: Consultation.clearConsultationForm,
    openConsultationAuditTrail: Consultation.openConsultationAuditTrail,
    toggleAuditDetail: Consultation.toggleAuditDetail,
    closeConsultationAuditTrail: Consultation.closeConsultationAuditTrail,
    closeConsultationForm: Consultation.closeConsultationForm,
    prepareConsultationEditView: Consultation.prepareConsultationEditView,
    scrollConsultationFormIntoView: Consultation.scrollConsultationFormIntoView,
    cancelConsultation: Consultation.cancelConsultation,
    normalizeBillingItemsToStructured: Consultation.normalizeBillingItemsToStructured,
    buildBillingItemsStructuredWithPackageSnapshot: Consultation.buildBillingItemsStructuredWithPackageSnapshot,
    saveConsultation: Consultation.saveConsultation,

    // ── consultation 掛號／應診／開診（Phase 6 子批 C）─────────────
    loadConsultationSystem: Consultation.loadConsultationSystem,
    setupAppointmentDatePicker: Consultation.setupAppointmentDatePicker,
    parseAppointmentPickerDate: Consultation.parseAppointmentPickerDate,
    formatLocalDateTimeInputValue: Consultation.formatLocalDateTimeInputValue,
    getDefaultAppointmentDateTimeValue: Consultation.getDefaultAppointmentDateTimeValue,
    searchPatientsForRegistration: Consultation.searchPatientsForRegistration,
    handlePatientSearchKeyDown: Consultation.handlePatientSearchKeyDown,
    handleHerbIngredientSearchKeyDown: Consultation.handleHerbIngredientSearchKeyDown,
    handleAcupointComboSearchKeyDown: Consultation.handleAcupointComboSearchKeyDown,
    selectPatientForRegistration: Consultation.selectPatientForRegistration,
    clearPatientSearch: Consultation.clearPatientSearch,
    showRegistrationModal: Consultation.showRegistrationModal,
    loadDoctorOptions: Consultation.loadDoctorOptions,
    closeRegistrationModal: Consultation.closeRegistrationModal,
    clearRegistrationForm: Consultation.clearRegistrationForm,
    confirmRegistration: Consultation.confirmRegistration,
    clearOldAppointments: Consultation.clearOldAppointments,
    loadTodayAppointments: Consultation.loadTodayAppointments,
    subscribeToAppointments: Consultation.subscribeToAppointments,
    loadConsultationForEdit: Consultation.loadConsultationForEdit,
    parseConsultationDate: Consultation.parseConsultationDate,
    getConsultationEffectiveDate: Consultation.getConsultationEffectiveDate,
    getConsultationEffectiveTimestamp: Consultation.getConsultationEffectiveTimestamp,
    formatConsultationDateTime: Consultation.formatConsultationDateTime,
    createAppointmentRow: Consultation.createAppointmentRow,
    getStatusInfo: Consultation.getStatusInfo,
    getOperationButtons: Consultation.getOperationButtons,
    confirmPatientArrival: Consultation.confirmPatientArrival,
    removeAppointment: Consultation.removeAppointment,
    cancelWaiting: Consultation.cancelWaiting,
    startConsultation: Consultation.startConsultation,
    continueConsultation: Consultation.continueConsultation,

    // Phase 6 子批 D1 — profile.js
    normalizePatientMedicalProfile: Consultation.normalizePatientMedicalProfile,
    hasPatientMedicalProfileContent: Consultation.hasPatientMedicalProfileContent,
    clearPatientMedicalProfileForm: Consultation.clearPatientMedicalProfileForm,
    collectPatientMedicalProfileFromForm: Consultation.collectPatientMedicalProfileFromForm,
    populatePatientMedicalProfileForm: Consultation.populatePatientMedicalProfileForm,
    formatPatientMedicalProfileSectionSummary: Consultation.formatPatientMedicalProfileSectionSummary,
    buildPatientMedicalProfileLegacySummary: Consultation.buildPatientMedicalProfileLegacySummary,
    mergePatientMedicalProfiles: Consultation.mergePatientMedicalProfiles,
    syncPatientMedicalProfileFromInquiryData: Consultation.syncPatientMedicalProfileFromInquiryData,
    invalidatePatientCaches: Consultation.invalidatePatientCaches,
    renderConsultationPatientMedicalInfo: Consultation.renderConsultationPatientMedicalInfo,
    getPatientMedicalProfileEditorTheme: Consultation.getPatientMedicalProfileEditorTheme,
    getPatientMedicalProfileSectionDescription: Consultation.getPatientMedicalProfileSectionDescription,
    getPatientMedicalProfileSectionEnglishTitle: Consultation.getPatientMedicalProfileSectionEnglishTitle,
    getPatientMedicalProfileSectionNotePlaceholder: Consultation.getPatientMedicalProfileSectionNotePlaceholder,
    ensureConsultationMedicalHistoryEditorContent: Consultation.ensureConsultationMedicalHistoryEditorContent,
    clearConsultationMedicalHistoryEditorForm: Consultation.clearConsultationMedicalHistoryEditorForm,
    populateConsultationMedicalHistoryEditorForm: Consultation.populateConsultationMedicalHistoryEditorForm,
    collectConsultationMedicalHistoryEditorForm: Consultation.collectConsultationMedicalHistoryEditorForm,
    getCurrentConsultationPatientId: Consultation.getCurrentConsultationPatientId,
    openConsultationMedicalHistoryEditor: Consultation.openConsultationMedicalHistoryEditor,
    closeConsultationMedicalHistoryEditor: Consultation.closeConsultationMedicalHistoryEditor,
    saveConsultationMedicalHistory: Consultation.saveConsultationMedicalHistory,

    // Phase 6 子批 D3 — access.js
    isGeneralRegistrationDoctorValue: Consultation.isGeneralRegistrationDoctorValue,
    isGeneralRegistrationAppointment: Consultation.isGeneralRegistrationAppointment,
    isGeneralRegistrationConsultation: Consultation.isGeneralRegistrationConsultation,
    isGeneralRegistrationContext: Consultation.isGeneralRegistrationContext,
    shouldHideGeneralRegistrationDoctorInfo: Consultation.shouldHideGeneralRegistrationDoctorInfo,
    getGeneralRegistrationSourceLabel: Consultation.getGeneralRegistrationSourceLabel,
    consultationHasPrescription: Consultation.consultationHasPrescription,
    canCurrentUserAccessGeneralRegistration: Consultation.canCurrentUserAccessGeneralRegistration,
    canCurrentUserViewGeneralRegistration: Consultation.canCurrentUserViewGeneralRegistration,
    canCurrentUserViewConsultationEntry: Consultation.canCurrentUserViewConsultationEntry,
    getAppointmentResponsibleDoctorUsername: Consultation.getAppointmentResponsibleDoctorUsername,
    canDoctorViewAppointment: Consultation.canDoctorViewAppointment,
    getRegistrationDoctorMeta: Consultation.getRegistrationDoctorMeta,
    getConsultationDoctorUsername: Consultation.getConsultationDoctorUsername,
    canCurrentUserEditMedicalRecordEntry: Consultation.canCurrentUserEditMedicalRecordEntry,
    getMedicalRecordEditAccessScope: Consultation.getMedicalRecordEditAccessScope,
    getMedicalRecordEditButtonLabel: Consultation.getMedicalRecordEditButtonLabel,
    setConsultationEditRestrictionState: Consultation.setConsultationEditRestrictionState,
    isMedicalRecordInCurrentClinic: Consultation.isMedicalRecordInCurrentClinic,
    getMedicalRecordEditWindowStatus: Consultation.getMedicalRecordEditWindowStatus,
    buildDirectConsultationEditContext: Consultation.buildDirectConsultationEditContext,
    getMainSymptomFromResult: Consultation.getMainSymptomFromResult,
    generateSymptomSummaryFromInquiry: Consultation.generateSymptomSummaryFromInquiry,
    generateHistorySummaryFromInquiry: Consultation.generateHistorySummaryFromInquiry,
    loadInquiryOptions: Consultation.loadInquiryOptions,
    canModifyPackageItems: Consultation.canModifyPackageItems,

    // Phase 6 子批 D2 — postvisit.js
    changeConsultationHistoryPage: Consultation.changeConsultationHistoryPage,
    closeMedicalHistoryModal: Consultation.closeMedicalHistoryModal,
    collectPackageUseRecordsFromConsultation: Consultation.collectPackageUseRecordsFromConsultation,
    getPackageBaseName: Consultation.getPackageBaseName,
    resolveConsultationPackageUseRemaining: Consultation.resolveConsultationPackageUseRemaining,
    resolveConsultationWalletBalance: Consultation.resolveConsultationWalletBalance,
    buildConsultationBillingDisplayHtml: Consultation.buildConsultationBillingDisplayHtml,
    withdrawConsultation: Consultation.withdrawConsultation,
    editMedicalRecord: Consultation.editMedicalRecord,
    editMedicalRecordByConsultationId: Consultation.editMedicalRecordByConsultationId,
    buildPackageWalletCombinedSection: Consultation.buildPackageWalletCombinedSection,
    bindPatientDetailClinicSelector: Consultation.bindPatientDetailClinicSelector,
    bindPackageHeaderButtons: Consultation.bindPackageHeaderButtons,
    loadPatientConsultationSummary: Consultation.loadPatientConsultationSummary
};

Object.assign(window, FACADE);
